export interface Tour {
  id: string
  title: string
  slug: string
  location: string
  country: string
  region: 'nederland' | 'europa' | 'wereld'
  date: string
  duration: string
  category: string
  description: string
  shortDescription: string
  highlights: string[]
  includes: string[]
  image: string
  gallery: string[]
}

export const tours: Tour[] = [
  {
    id: '1',
    title: 'Amsterdam Marathon Training Kamp',
    slug: 'amsterdam-marathon-kamp',
    location: 'Amsterdam',
    country: 'Nederland',
    region: 'nederland',
    date: 'September 2026',
    duration: '5 dagen',
    category: 'Hardlopen',
    shortDescription: 'Train op de iconische routes van Amsterdam en race door de grachtenstad.',
    description: 'Een volledig begeleide trainingskamp ter voorbereiding op de Amsterdam Marathon. Loop langs de prachtige grachten, door de Vondelpark en door de historische binnenstad. Professionele hardloopcoaches begeleiden u dagelijks, met groepsloopjes in de ochtend en tactische sessies in de middag.',
    highlights: ['Dagelijkse begeleide trainingsloops', 'Hardloopanalyse & looptechniek', 'Route door de grachten en Vondelpark', 'Voedingsworkshop voor duursporters'],
    includes: ['5 nachten hotel Amsterdam centrum', 'Dagelijkse trainingssessies', 'Transfers', 'Sportvoedingspakket'],
    image: '/images/tours/amsterdam-marathon-kamp.jpg',
    gallery: [
      '/images/tours/dutch-classics-cycling.jpg',
      '/images/tours/nyc-marathon-stage.jpg',
    ],
  },
  {
    id: '2',
    title: 'Nederlandse Wielerklassiekers Fietstour',
    slug: 'dutch-classics-cycling',
    location: 'Utrecht – Limburg',
    country: 'Nederland',
    region: 'nederland',
    date: 'April 2026',
    duration: '7 dagen',
    category: 'Wielrennen',
    shortDescription: 'Fiets de routes van de Nederlandse voorjaarswedstrijden door polder en heuvelland.',
    description: 'Rijd de exacte parcoursen van de Nederlandse wielerklassiekers voordat de professionele renners langskomen. Van de vlakke polderroutes in Utrecht tot de glooiende heuvels van Limburg – dit is de ideale combinatie van sportief fietsen en het beleven van de koerscultuur.',
    highlights: ['Fietsen op het Amstel Gold Race-parcours', 'Begeleide groepsritten elke dag', 'Wielercoach met video-analyse', 'Bezoek aan het Nederlands Wielermuseum'],
    includes: ['7 nachten hotel', 'Dagelijkse fietsroutes met gids', 'Fietshuur of eigen fiets welkom', 'Sportmaaltijden'],
    image: '/images/tours/dutch-classics-cycling.jpg',
    gallery: [],
  },
  {
    id: '3',
    title: 'Formule 1 Pitlane Kamp Zandvoort',
    slug: 'f1-zandvoort-kamp',
    location: 'Zandvoort',
    country: 'Nederland',
    region: 'nederland',
    date: 'Augustus 2026',
    duration: '3 dagen',
    category: 'Motorsport',
    shortDescription: 'Verken het Circuit Zandvoort, rij kartbanen en beleef de techniek van F1.',
    description: 'Een unieke sportbeleving rondom het iconische Circuit Zandvoort. Rij kartraces op professionele kartbanen, volg een exclusieve rondleiding door de pitlane en ontdek de werking van een Formule 1-weekend van binnen. Inclusief rijsimulator en gesprek met een oud-coureur.',
    highlights: ['Exclusieve pitlane & paddock rondleiding', 'Professionele kartraces', 'F1 rijsimulator sessie', 'Gesprek met oud-profcoureur'],
    includes: ['3 nachten hotel Zandvoort', 'Kartraces inclusief', 'Rondleidingen', 'Transfers'],
    image: '/images/tours/f1-zandvoort-kamp.jpg',
    gallery: [],
  },
  {
    id: '4',
    title: 'Tour de France Wielertocht Alpen',
    slug: 'tour-de-france-alpen',
    location: 'Alpe d\'Huez – Grenoble',
    country: 'Frankrijk',
    region: 'europa',
    date: 'Juli 2026',
    duration: '6 dagen',
    category: 'Wielrennen',
    shortDescription: 'Beklim de legendarische Alpencols op het parcours van de Tour de France.',
    description: 'Fiets de legendarische bergritten van de Tour de France op exact dezelfde wegen als de profs. Van Alpe d\'Huez tot Col de la Croix de Fer – begeleide dagritten met een wielercoach, herstelmaaltijden en overnachtingen in berghotels langs het parcours.',
    highlights: ['Beklimming Alpe d\'Huez (21 bochten)', 'Col de la Croix de Fer en Col du Glandon', 'Dagelijkse begeleide ritten', 'Live etappe bijwonen'],
    includes: ['6 nachten berghotel', 'Fietsbegeleiding', 'Transfers en fietsbus', 'Sportvoeding dagelijks'],
    image: '/images/tours/tour-de-france-alpen.jpg',
    gallery: [],
  },
  {
    id: '5',
    title: 'Roland Garros Tenniskamp Parijs',
    slug: 'roland-garros-tennis',
    location: 'Parijs',
    country: 'Frankrijk',
    region: 'europa',
    date: 'Mei 2026',
    duration: '5 dagen',
    category: 'Tennis',
    shortDescription: 'Train op Parijse gravelbanen en bezoek het Grand Slam-complex van Roland Garros.',
    description: 'Combineer tenniscoaching op echte Parijse gravelbanen met een bezoek aan het Roland Garros-complex. Professionele tennistrainers begeleiden u in kleine groepen, terwijl u kennismaakt met de techniek van het gravelspel. Inclusief rondleiding door het toernooi-terrein en bezoek aan de tennismusea.',
    highlights: ['Tennis training op gravelbanen', 'Rondleiding Roland Garros-complex', 'Video-analyse looptechniek', 'Parijs stadsbezoek met sporttintje'],
    includes: ['5 nachten hotel Parijs', 'Tennissessies dagelijks', 'Rondleiding complex', 'Transfers'],
    image: '/images/tours/roland-garros-tennis.jpg',
    gallery: [],
  },
  {
    id: '6',
    title: 'Ronde van Vlaanderen Fietstour',
    slug: 'ronde-van-vlaanderen',
    location: 'Gent – Oudenaarde',
    country: 'België',
    region: 'europa',
    date: 'April 2026',
    duration: '4 dagen',
    category: 'Wielrennen',
    shortDescription: 'Fiets de beroemde kasseisecties en hellingen van De Ronde.',
    description: 'De Ronde van Vlaanderen is de heiligste wielerklassieke. Beleef de ruwe kasseien van de Paterberg en de Koppenberg zelf op de fiets, begeleid door een oud-profrenner. Inclusief een VIP plek langs de Muur van Geraardsbergen en diner in klassieke Vlaamse wielerherberg.',
    highlights: ['Fiets de kasseien van Paterberg en Koppenberg', 'Oud-profrenner als gids', 'Muur van Geraardsbergen', 'Flandrien-diner in historische herberg'],
    includes: ['4 nachten hotel Oudenaarde', 'Dagelijkse fietsroutes', 'Profgids', 'Begeleiding'],
    image: '/images/tours/ronde-van-vlaanderen.jpg',
    gallery: [],
  },
  {
    id: '7',
    title: 'Pyreneeën Klimmersstage',
    slug: 'pyreneeen-klimmersstage',
    location: 'Pyreneeën',
    country: 'Spanje / Frankrijk',
    region: 'europa',
    date: 'Juni 2026',
    duration: '8 dagen',
    category: 'Wielrennen',
    shortDescription: 'Fiets de zwaarste cols van de Pyreneeën in een begeleide groepsstage.',
    description: 'Acht dagen lang fietsen door de Pyreneeën langs de meest iconische bergpassen uit de wielergeschiedenis. Col du Tourmalet, Col d\'Aubisque en Col d\'Aspin staan op het programma. Een kleine groep, dagelijkse begeleiding en professionele verzorging maken dit tot de ultieme bergfietservaring.',
    highlights: ['Col du Tourmalet (2115m)', 'Col d\'Aubisque en Col d\'Aspin', 'Kleine groep (max 12 deelnemers)', 'Dagelijkse wielercoaching'],
    includes: ['8 nachten hotel/pension', 'Fietsbegeleiding', 'Fietsondersteuningswagen', 'Maaltijden inbegrepen'],
    image: '/images/tours/pyreneeen-klimmersstage.jpg',
    gallery: [],
  },
  {
    id: '8',
    title: 'Wimbledon Tennis Academy Londen',
    slug: 'wimbledon-tennis-academy',
    location: 'Londen',
    country: 'Engeland',
    region: 'europa',
    date: 'Juli 2026',
    duration: '5 dagen',
    category: 'Tennis',
    shortDescription: 'Train op grasbanen in Londen en bezoek het heiligste tennisstadion ter wereld.',
    description: 'Tennis op gras is een kunstvorm. In Londen traint u onder begeleiding van ervaren coaches op echte grasvelden – dezelfde ondergrond als Wimbledon. Inclusief een rondleiding door het All England Club en een bezoek aan de beroemde Wimbledon Lawn Tennis Museum.',
    highlights: ['Training op professionele grasbanen', 'Rondleiding All England Club & museum', 'Serve en volley coaching', 'Londen sportreis met Hyde Park run'],
    includes: ['5 nachten hotel Londen', 'Tennissessies', 'Rondleidingen', 'Transfers'],
    image: '/images/tours/wimbledon-tennis-academy.jpg',
    gallery: [],
  },
  {
    id: '9',
    title: 'Kitzbühel Ski & Hahnenkamm Kamp',
    slug: 'kitzbuehel-ski-kamp',
    location: 'Kitzbühel',
    country: 'Oostenrijk',
    region: 'europa',
    date: 'Januari 2027',
    duration: '6 dagen',
    category: 'Wintersport',
    shortDescription: 'Ski op de beroemde Streif-piste en train in het skigebied van Kitzbühel.',
    description: 'Kitzbühel is de skiwereld in optima forma. Zes dagen lang skiet u op de Streif – de gevaarlijkste piste ter wereld – begeleid door gecertificeerde skileraren. Inclusief off-piste avonturen in de omliggende bergen en après-ski in de historische Tiroler stad.',
    highlights: ['Ski-instructie op de Streif', 'Off-piste avontuur met berggids', 'Skianalyse met videofeedback', 'Après-ski in authentiek Tirol'],
    includes: ['6 nachten ski-in/ski-out hotel', 'Skipas 6 dagen', 'Skileraren dagelijks', 'Transfers'],
    image: '/images/tours/kitzbuehel-ski-kamp.jpg',
    gallery: [],
  },
  {
    id: '10',
    title: 'Tokyo Marathon Training Ervaring',
    slug: 'tokyo-marathon-training',
    location: 'Tokyo',
    country: 'Japan',
    region: 'wereld',
    date: 'Februari 2027',
    duration: '9 dagen',
    category: 'Hardlopen',
    shortDescription: 'Bereid u voor op de Tokyo Marathon met professionele training in Japan.',
    description: 'De Tokyo Marathon is een World Marathon Major. Negen dagen lang combineert u intensieve looptraining met de fascinerende Japanse cultuur. Ochtendtraining in de Yoyogi Park, looproutes langs tempels en een uitgebreid tapering-programma voor de race zelf.',
    highlights: ['Begeleide trainingsloops in Yoyogi Park', 'Route langs Asakusa Tempel', 'Japanse herstelrituelen (onsen)', 'Race-dagbegeleiding op het parcours'],
    includes: ['9 nachten hotel Tokyo', 'Hardloopbegeleiding', 'Vluchten', 'Cultureel programma'],
    image: '/images/tours/tokyo-marathon-training.jpg',
    gallery: [],
  },
  {
    id: '11',
    title: 'New York City Marathon Stage',
    slug: 'nyc-marathon-stage',
    location: 'New York City',
    country: 'USA',
    region: 'wereld',
    date: 'Oktober 2026',
    duration: '7 dagen',
    category: 'Hardlopen',
    shortDescription: 'Train op de vijf boroughs van New York ter voorbereiding op de NYC Marathon.',
    description: 'New York City is de ultieme marathonstad. Wij begeleiden u door de vijf stadsdelen op de exacte parcourssecties van de New York City Marathon – van Staten Island via Brooklyn en Queens tot het finishpunt in Central Park. Inclusief loopcoaching, voedingsadvies en stadsbezienswaardigheden.',
    highlights: ['Training op NYC Marathon-route', 'Run door Central Park en Brooklyn Bridge', 'Hardloopcoach met marathonervaring', 'NYC sightseeing via hardlopen'],
    includes: ['7 nachten hotel Manhattan', 'Dagelijkse hardloopsessies', 'Vluchten', 'Transfers'],
    image: '/images/tours/nyc-marathon-stage.jpg',
    gallery: [],
  },
  {
    id: '12',
    title: 'Barcelona Voetbal Stadion Tour',
    slug: 'barcelona-voetbal-stadion',
    location: 'Barcelona',
    country: 'Spanje',
    region: 'europa',
    date: 'Mei 2026',
    duration: '4 dagen',
    category: 'Voetbal',
    shortDescription: 'Verken het Spotify Camp Nou en train op voetbalvelden van FC Barcelona.',
    description: 'Een unieke sportbelevingstour in Barcelona voor voetbalfans en recreatieve spelers. Bezoek het vernieuwde Spotify Camp Nou, volg een exclusieve rondleiding door de trainingsaccommodaties van FC Barcelona en speel zelf voetbal op professionele velden in Barcelona. Met een UEFA-gecertificeerde voetbaltrainer.',
    highlights: ['Exclusieve rondleiding Spotify Camp Nou', 'Training op La Masia-velden', 'Voetbaltactiek sessie met UEFA-coach', 'Bezoek FC Barcelona Museum'],
    includes: ['4 nachten hotel Barcelona', 'Voetbaltraining', 'Stadionrondleiding', 'Transfers'],
    image: '/images/tours/barcelona-voetbal-stadion.jpg',
    gallery: [],
  },
  {
    id: '13',
    title: 'Dubai Extreme Sportavontuur',
    slug: 'dubai-extreme-sport',
    location: 'Dubai',
    country: 'VAE',
    region: 'wereld',
    date: 'November 2026',
    duration: '6 dagen',
    category: 'Extreme Sports',
    shortDescription: 'Skydiven, kitesurfen en desert buggy\'s in het futuristische Dubai.',
    description: 'Dubai combineert luxe met adrenaline als geen andere plek. Zes dagen lang beleeft u de meest extreme sporten: skydiven met uitzicht over de Palm, kitesurfen op de Arabische Zee, sand boarding in de Sahara-duinen en een nacht camping in de woestijn. Begeleiding door gecertificeerde extreme sportinstructeurs.',
    highlights: ['Skydiven boven de Palm Jumeirah', 'Kitesurfen op de Arabische Zee', 'Sand boarding in de woestijnduinen', 'Desert buggy raid met gids'],
    includes: ['6 nachten luxe hotel', 'Alle sportactiviteiten', 'Vluchten', 'VIP transfers Dubai'],
    image: '/images/tours/dubai-extreme-sport.jpg',
    gallery: [],
  },
  {
    id: '14',
    title: 'Schotland Golf & Wandeltour',
    slug: 'schotland-golf-wandelen',
    location: 'St Andrews – Highlands',
    country: 'Schotland',
    region: 'europa',
    date: 'September 2026',
    duration: '7 dagen',
    category: 'Golf',
    shortDescription: 'Golf op de heilige links van St Andrews en wandel de Schotse Highlands.',
    description: 'Schotland is de geboortegrond van golf. Speel op de iconische Old Course van St Andrews, wandel door de dramatische Schotse Highlands langs lochans en kastelen, en verblijf in authentieke country lodges. Inclusief golfpro-begeleiding en wandelgidsen voor de Highlandroutes.',
    highlights: ['Ronde op de Old Course St Andrews', 'Wandeling door Glen Coe', 'Golfpro-coaching', 'Whisky proeverij in distilleerderij'],
    includes: ['7 nachten country hotel', 'Greenfees inbegrepen', 'Wandelgidsen', 'Vluchten'],
    image: '/images/tours/schotland-golf-wandelen.jpg',
    gallery: [],
  },
  {
    id: '15',
    title: 'Surf & Yoga Kamp Portugal',
    slug: 'surf-yoga-portugal',
    location: 'Nazaré – Peniche',
    country: 'Portugal',
    region: 'europa',
    date: 'Oktober 2026',
    duration: '7 dagen',
    category: 'Surf',
    shortDescription: 'Surf de golven van Nazaré en herstel met yoga aan de Atlantische kust.',
    description: 'Portugal is het surftop van Europa. In Nazaré – bekend om de grootste golven ter wereld – worden beginners en gevorderden begeleid door ISA-gecertificeerde surfinstructeurs. Ochtenden op de golven, middagen met yoga op het strand en avonden met verse vis aan de Atlantische kust.',
    highlights: ['Dagelijkse surflessen ISA-instructor', 'Yoga op het strand bij zonsopgang', 'Bezoek aan Nazaré grote golf-spot', 'Waterfotografie sessie'],
    includes: ['7 nachten surfhostel/hotel', 'Surfboard en wetsuit', 'Yoga sessies dagelijks', 'Maaltijden'],
    image: '/images/tours/surf-yoga-portugal.jpg',
    gallery: [],
  },
  {
    id: '16',
    title: 'Johan Cruijff Arena Voetbaltour',
    slug: 'johan-cruijff-arena-tour',
    location: 'Amsterdam',
    country: 'Nederland',
    region: 'nederland',
    date: 'Het hele jaar',
    duration: '2 dagen',
    category: 'Voetbal',
    shortDescription: 'Verken de Johan Cruijff Arena en train op de velden van Ajax.',
    description: 'De Johan Cruijff Arena is één van de meest moderne voetbalstadions ter wereld. Exclusieve rondleiding achter de schermen: kleedkamers, persconferentieruimte, veld en hospitality-suite. Gevolgd door een voetbaltraining op de Ajax-kunstgrasvelden onder begeleiding van een UEFA-gecertificeerde trainer.',
    highlights: ['Achterkantoor rondleiding Johan Cruijff Arena', 'Training op Ajax-velden', 'Tactiekworkshop met oud-speler', 'Ajax Museum bezoek'],
    includes: ['2 nachten hotel Amsterdam', 'Stadiontour', 'Voetbaltraining', 'Transfers'],
    image: '/images/tours/johan-cruijff-arena-tour.jpg',
    gallery: [],
  },
  {
    id: '17',
    title: 'Dolomiten Mountainbike Stage',
    slug: 'dolomiten-mountainbike',
    location: 'Dolomiten',
    country: 'Italië',
    region: 'europa',
    date: 'Augustus 2026',
    duration: '6 dagen',
    category: 'Mountainbike',
    shortDescription: 'Mountainbiken door het UNESCO-werelderfgoed van de Italiaanse Dolomiten.',
    description: 'De Dolomiten zijn de mooiste bergen van Europa voor mountainbikers. Zes dagen rijden door spectaculaire dolomieten-landschappen langs rifugi, over singletrack paden en door alpenweiden. Begeleide groepsritten voor alle niveaus, met e-bike optie voor de zwaardere trails.',
    highlights: ['Singletrack routes boven de boomgrens', 'Rifugio overnachting in de bergen', 'Technische mountainbike coaching', 'E-bike optie beschikbaar'],
    includes: ['6 nachten hotel/rifugio', 'Mountainbike huur', 'Begeleiding', 'Lunches op de route'],
    image: '/images/tours/dolomiten-mountainbike.jpg',
    gallery: [],
  },
  {
    id: '18',
    title: 'Marokko Woestijn Hardlooptour',
    slug: 'marokko-woestijn-hardlopen',
    location: 'Sahara – Marrakech',
    country: 'Marokko',
    region: 'wereld',
    date: 'Maart 2027',
    duration: '8 dagen',
    category: 'Hardlopen',
    shortDescription: 'Loop door de Sahara-woestijn op de route van de Marathon des Sables.',
    description: 'Marokko biedt een van de meest uitdagende hardlooplandschappen ter wereld. Op de route van de beroemde Marathon des Sables loopt u door de Sahara-duinen, over rotsachtige hammada-vlaktes en door Berber-dorpen. Acht dagen van sport, avontuur en authentieke Marokkaanse cultuur.',
    highlights: ['Hardlopen in de Sahara-duinen', 'Berber bivak overnachting in de woestijn', 'Route Marathon des Sables', 'Marrakech stadstour en soeks'],
    includes: ['8 nachten hotel/bivak', 'Begeleide hardlooproutes', 'Vluchten', 'Begeleiding'],
    image: '/images/tours/marokko-woestijn-hardlopen.jpg',
    gallery: [],
  },
]

export function getTourBySlug(slug: string): Tour | undefined {
  return tours.find(tour => tour.slug === slug)
}

export function getToursByRegion(region: Tour['region']): Tour[] {
  return tours.filter(tour => tour.region === region)
}

export function getAllCategories(): string[] {
  return [...new Set(tours.map(tour => tour.category))]
}
